src/lib.rs
Implements standard operations like `BitAnd`, `BitOr`, `BitXor` for
Bitmap. Allows to use syntactic sugar instead of function calls when
working with a Bitmap.
=> Add standard operations for bitmaps for Bitmap

Cargo.toml, benches/performance_comparison.rs
Compares CRoaring Rust wrapper performance with Rust native roaring library implementation on common operations.
Fixes #6
=> Add performance comparison benchmark

benches/performance_comparison.rs
First of all, thanks a lot for adding these performance comparison benchmarks 😄 it's great to finally see what the performance of `roaring-rs` is really like.
I was just using these to try and see if all the `#[inline]` attributes I added to `roaring-rs` way back when actually made a difference (surprisingly, yes, quite a big difference) and noticed that there seemed to be a large discrepancy between the `{and,or,xor}_rust_roaring` and `{and,or,xor}_new_rust_roaring` benchmarks, which seemed odd since internally the non-inplace versions of these in `roaring-rs` just clone the bitmap then run the inplace version.
Taking a look I noticed the benchmarks didn't actually call the non-inplace versions, they just collected the iterated variants up. There aren't actually inherent methods on …
=> Fix roaring-rs benchmarks to use specialized operators

benches/performance_comparison.rs, croaring-sys/src/lib.rs, src/iter.rs, src/lib.rs, src/ops.rs
Returns Bitmap values in ascending order. Drops `Bitmap#into_iter()`, reason:
we cannot allow conversion into iterator with C based iterators as they modify
the underlying bitmap (https://github.com/RoaringBitmap/CRoaring/blob/2854bf777d6285994ea212f653cfadfce7afe83e/include/roaring/roaring.h#L450-L451).
Introduces `Bitmap#iter()` which allows to iterate over `Bitmap`. The Bitmap should not be modified while iterating.
Also: extracted iterator related functionality to `iter` module.
=> Use C api for Bitmap iterator

README.md, benches/benches.rs, src/imp.rs, src/lib.rs, src/ops.rs, tests/lib.rs
As reported - https://github.com/saulius/croaring-rs/issues/16 - fixes use after bug with with as_slice. `as_slice` is replaced with `to_vec`.
Fixes #16.
=> Bitmap#as_slice -> Bitmap#to_vec

src/imp.rs
Adding tests and usage examples for `*_cardinality` and `jaccard_index`
methods.
=> Add tests for *_cardinality methods

src/imp.rs, tests/lib.rs
Before this fix, returned vec had length of 0. So one could not actually use serialized bitmap easily (without manually invoking set_len).
=> Set vec size when serializing bitmap

src/lib.rs
According CRoaring documentation (https://github.com/RoaringBitmap/CRoaring#thread-safety) Bitmap follows the semantic of Send and
Sync. Rust doesn't implement those traits for it, but it should be safe to
mark those traits as implemented.
Fixes  #37
=> Implement Send and Sync for Bitmap

src/bitmap/imp.rs, tests/lib.rs
Adds call to bitmap clear which allows faster clearing without a re-allocation or in place intersection.
=> Add bitmap.clear()

README.md, croaring-sys/build.rs
If you build binaries on one machine and run them on a different one
it's possible that the latter machine might lack certain CPU
instructions of the build machine. In such instances `ROARING_ARCH`
environment variables allows to target end user machine's CPU
instruction set.
Also removed optimisation level as it's controlled by `cargo` build release mode and `cc-rs`.
Solves #60 #61
=> Allow to specify target CPU architecture

croaring/src/bitmap/ops.rs
I found that displaying the debug format of a `Bitmap` was really slow when bitmaps were big, I found out that there wasn't any optimization on that, I implemented it.
=> Implement a better Debug for the Bitmap

.github/workflows/rust.yml
49ac9ef says:
>Disable CI run on Windows
>
>Apparently Microsoft introduced a bug Visual Studio's distribution.
>More at:
>https://github.com/microsoft/STL/issues/1300
>
>Revert this when things get better.
I am pleased to report that things have gotten better (https://github.com/microsoft/STL/issues/1300#issuecomment-789542493) and excited to provide you with a revert. :)
This change passes CI for me: https://github.com/trevyn/croaring-rs/runs/2139234443
xref: https://github.com/mimblewimble/grin/pull/3596
=> Revert "Disable CI run on Windows"

croaring-sys/Cargo.toml, croaring-sys/build.rs, croaring-sys/src/lib.rs
* Use allowlists to only include roaring items
* Include docs
* Output extra cargo metadata to tell it about the environment variable
our build script uses
=> Improvements to croaring-sys

croaring/src/bitmap/iter.rs, croaring/src/treemap/iter.rs
Also, implement `FromIterator` for Treemap in terms of `Extend`, since `Treemap::of` just calls `add` repeatedly, there's no reason to collect into a vec first.
=> Implement Extend for Bitmap and Treemap

croaring/src/bitmap/iter.rs, croaring/src/treemap/imp.rs
Fixes #51
Also, use the new function in the implementation of `Treemap::to_vec`
=> Expose the ability to read multiple items from an iterator, for performance

croaring-sys/build.rs
Per the [cc docs][1], we shouldn't be passing libroaring.a, and should instead
be passing just "roaring"
> The output string argument determines the file name for the compiled
> library. The Rust compiler will create an assembly named
> “lib”+output+“.a”. MSVC will create a file named output+“.lib”.
>
> For backwards compatibility, if output starts with “lib” and ends with
> “.a”, a second “lib” prefix and “.a” suffix do not get added on, but
> this usage is deprecated; please omit lib and .a in the argument that
> you pass.
[1]: https://docs.rs/cc/1.0.73/cc/struct.Build.html#method.compile
=> Pass only the base library name to cc::Build::compile

croaring/src/bitmap/imp.rs, croaring/src/bitmap/iter.rs, croaring/src/bitmap/mod.rs, croaring/src/bitmap/ops.rs
Rather than `Bitmap` being a wrapper over a heap allocated `*roaring_bitmap_t`, wrap the `roaring_bitmap_t` type directly. This matches the c++ wrapper, and should reduce pointer-chasing by a little bit.
I _think_ this is backwards compatible, but I wouldn't bet my life savings on that.
=> Unbox bitmap

croaring/src/bitmap/imp.rs, croaring/src/bitmap/ops.rs, croaring/src/treemap/imp.rs, croaring/src/treemap/ops.rs
`Bitmap::flip` and `Bitmap::contains_range` should only require `&self`, not `&mut self`. This should be a backwards compatible change, it only increases the set of programs accepted.
Additionally, try to remove mutability from examples where possible, to prevent this from happening again.
Also, correct the documentation of `Bitmap::minimum` and `Bitmap::maximum`
=> `Bitmap::flip` does not require `&mut self`

croaring/src/bitmap/imp.rs, croaring/src/bitmap/ops.rs
This changes the function used to allocate heap allocated bitmaps (`malloc`/`free` -> `roaring_malloc`/`roaring_free`). It also added a new function: `roaring_bitmap_add_offset`, which we now expose as `Bitmap::add_offset`
=> Bump croaring to 0.5.0

croaring/src/bitmap/imp.rs, croaring/src/bitmap/iter.rs, croaring/src/bitmap/lazy.rs, croaring/src/bitmap/mod.rs, croaring/src/bitmap/ops.rs, croaring/src/bitmap/view.rs
Like described in [this blog post][1], it can be useful to add doc aliases for the wrapped c functions, so someone who knows the c api can more easily find the equivalents in the safe wrapper
[1]: https://blog.guillaume-gomez.fr/articles/2020-12-04+doc%28alias%29+is+stable+and+it%27s+gonna+be+super+useful%21
=> Add doc alias to corresponding c functions

croaring/src/bitmap/serialization.rs, croaring/tests/lib.rs
We weren't taking into account existing data in `serialize_into` implementations. This fixes that, and adds tests for this case.
=> Fix serialization when serializing into a vec with contents

.gitignore, croaring/src/treemap/imp.rs
=> Port is_subset to`TreeMap`

Cargo.toml, croaring-sys/build.rs, croaring/src/bitmap/imp.rs, croaring/src/bitmap/iter.rs, croaring/src/bitmap/mod.rs, croaring/src/bitmap/ops.rs, croaring/src/bitmap/serialization.rs, croaring/src/bitmap/view.rs, croaring/src/bitset/imp.rs, croaring/src/bitset/iter.rs, croaring/src/bitset/mod.rs, croaring/src/bitset/ops.rs, croaring/src/treemap/imp.rs, croaring/src/treemap/iter.rs, croaring/src/treemap/mod.rs
I believe this adds all the operations from C++'s Roaring64Map.
Additionally, fixes suggested by `cargo clippy -- -W clippy::pedantic`, mostly adding `must_use` to most functions where the function is only useful for its output.
=> Add missing operations to TreeMap

croaring/src/bitmap/mod.rs, croaring/src/bitmap/serialization.rs, croaring/src/lib.rs, croaring/src/serialization.rs, croaring/src/treemap/imp.rs, croaring/src/treemap/iter.rs, croaring/src/treemap/mod.rs, croaring/src/treemap/ops.rs, croaring/src/treemap/serialization.rs, croaring/tests/lib.rs
See #108 
Makes the changes from #106 for treemap.
This also adds some more doc comments to serialization types/functions, and does some misc clippy fixes for treemap functions.
=> Use a more idiomatic trait-based implementation of serialization for treemaps

croaring/src/lib.rs, croaring/src/treemap/iter.rs, croaring/src/treemap/mod.rs
Instead, it can still be accessed through `croaring::bitmap::BitmapIterator`, and often iterator types are exported through a submodule even when the type they iterate over is re-exported at a higher level.
Additionally, enforce doc comments everywhere, and add the few remaining missing docs.
@saulius, I think this is the last change I had in mind before `1.0`
=> Don't re-export BitmapIterator at the top level

.github/workflows/rust.yml, croaring/Cargo.toml
~~I'm seeing a few issues that I will fix in a minute, but I want to make sure this test would catch them in CI (if CI is allowed to run on my PR)~~ Ok that has to be approved, but it turns out CI as-is wouldn't have caught my issue anyway, but I'm including it here because it caught a different issue... keep reading for more explanation but I'm happy to take out whatever commits you'd like me to.
I upgraded a project I work on that uses `croaring` to move off of the yanked version `1.0.0`. I did this by running `cargo update -p croaring`, forgetting that `croaring-sys` would need an update too (and also forgetting to pass `--aggressive`).
The project's build started failing with these errors:
```
Compiling croaring v1.0.1
error[E0425]: cannot find function …
```
=> Add a CI job to check the minimal version constraints of direct dependencies

croaring/src/treemap/imp.rs, croaring/src/treemap/ops.rs, croaring/tests/lib.rs
And add a test which validates the expected behavior. This also found a doc test which was accidentally incorrect.
=> bugfix: Treemap.andnot would not include items with no container on rhs

croaring/src/treemap/imp.rs, croaring/tests/lib.rs
remove_range would remove the whole container if the first bitmap found in the range was the last bigmap touching the range, rather than just the first part of the container.
=> Treemap: remove_range would sometimes remove too much

Makefile, croaring/src/treemap/imp.rs
Also, update the way we do bindgen, see
https://github.com/rust-lang/rust-bindgen/issues/2760
=> Treemap: Avoid leaving empty bitmaps with binary operations

Cargo.lock, croaring-sys/Cargo.toml, croaring/Cargo.toml, fuzz/Cargo.lock, fuzz/fuzz_targets/deserialize.rs, fuzz/fuzz_targets/fuzz_ops.rs
Also, fix the fuzzer compiling.
The Roaring64 fuzzing found RoaringBitmap/CRoaring#635, probably going to wait for a fix for that before merging.
=> Bump sys version

.gitignore, Cargo.lock, Makefile, README.md, croaring-sys/CRoaring/bindgen_bundled_version.rs, croaring-sys/CRoaring/roaring.c, croaring-sys/CRoaring/roaring.h, croaring-sys/CRoaring/roaring.hh, croaring-sys/Cargo.toml, croaring/Cargo.toml, croaring/src/bitmap/imp.rs, croaring/src/bitmap/iter.rs, croaring/src/bitmap64/imp.rs, croaring/src/bitmap64/iter.rs, croaring/tests/roaring64.rs, fuzz/Cargo.lock
Add some tests which will fail until we get a 4.0.1 of CRoaring. Don't merge until we update again once CRoaring is fixed.
Also, include the matching CRoaring version in the readme and some clarification on versioning, this will hopefully help clarify somewhat the questions raised in #136. Link to the rendered added section: https://github.com/Dr-Emann/croaring-rs/blob/2_0_for_real/README.md#croaring-version
Fixes #136
=> 2 0 for real

.github/workflows/rust.yml, croaring/benches/benches.rs, fuzz/Cargo.lock
don't run a full benchmark, but do test fuzzers, and all targets in release mode (including benchmarks)
@saulius would like your thoughts, since you originally built the github CI.
=> rework ci testing

croaring/Cargo.toml, croaring/src/bitmap/mod.rs, croaring/src/bitmap64/ops.rs, fuzz/Cargo.lock, fuzz/fuzz_targets/deserialize.rs
Use new roaring64_bitmap_move_from_roaring32 function
=> Add From<Bitmap> for Bitmap64

croaring/Cargo.toml, croaring/src/lib.rs, croaring/src/rust_alloc.rs, croaring/tests/lib.rs, croaring/tests/roaring64.rs
In addition to adding testing to the integration tests, I tested with all the doc tests (which are more comprehensive) by using the `ctor` crate to automatically enable the rust alloc functions, and was able to run with ASAN without issues.
=> feat: enable configuring rust global alloc as croaring allocator
