RoaringBitmap/croaring-rs

croaring-sys/CRoaring/roaring.c
croaring-sys/CRoaring/roaring.h
croaring-sys/src/lib.rs

CRoaring update + FFI declaration fixes. Addition to https://github.com/saulius/croaring-rs/pull/7.
cc @lemire

CRoaring upgrade

---

croaring-sys/src/lib.rs
src/imp.rs
systest/src/main.rs

Implements new functions that were added in CRoaring 0.2.15.
Fixes https://github.com/saulius/croaring-rs/issues/22.

Implement Bitmap#minimum, maximum, rank, select

---

Cargo.toml
benches/performance_comparison.rs

Also some refactorings needed by new Rust versions.

Update dependency versions

---

.travis.yml
croaring-sys/build.rs

Conditionally set CRoaring build flags. Test on multiple OSes and compiler flavours.

Multi-OS support

---

croaring-sys/Cargo.toml
tests/lib.rs

`bindgen = ">= 0.37, <= 0.49"`

Update version on bindgen dep

---

src/bitmap/imp.rs
src/treemap/imp.rs

minimum/maximum should return None when bitmap is empty, 0 and MAX_INT are valid elements.

minimum/maximum return Option

---

Cargo.toml
croaring-sys/Cargo.toml

Update bindgen to 0.52.0

---

src/bitmap/imp.rs

Uses `roaring_bitmap_portable_deserialize_safe` for safe deserialization. Implements `try_deserialize` function.

Safe deserialization

---

croaring-sys/Cargo.toml

Update bindgen to v0.56.0

---

.github/workflows/rust.yml

Set LLVM path on Windows for CI

---

croaring-sys/Cargo.toml
croaring-sys/build.rs
croaring/src/bitmap/imp.rs

Since 0.3.0 CRoaring has runtime dispatching for enabling architecture dependent optimizations.

Upgrade to 0.3.1

---

croaring-sys/Cargo.toml
croaring/Cargo.toml
croaring/benches/benches.rs
croaring/tests/lib.rs

First of all, thank you so much for great work.
This PR update croaring to v0.3.3 and other deps. Could you please review :)

Update croaring 0.3.3 and other dependencies

---

croaring/src/bitmap/iter.rs

This does depend on `roaring_uint32_iterator_s` not being self-referential, and movable in memory, but that seems like a safe assumption.

Embed an iterator directly, rather than through a pointer

---

croaring/src/bitmap/imp.rs

This allows passing `a..=b`, `..=b`, etc to all range-expecting functions
*NOTE* This is a breaking change

Use RangeBounds to accept ranges

---

croaring/src/bitmap/imp.rs
croaring/src/bitmap/iter.rs
croaring/src/bitmap/lazy.rs
croaring/src/bitmap/mod.rs
croaring/src/bitmap/ops.rs

Add `BitmapIterator::reset_at_or_after`, `Bitmap::from_range`, `Bitmap::from_range_with_step`, and `Bitmap::intersect_with_range`.

Adding missing bindings

---

.github/workflows/rust.yml
croaring/benches/performance_comparison.rs

LLVM does not seem to be installed by default anymore

---

croaring/src/treemap/imp.rs
croaring/tests/lib.rs

ordering fix for boolean expression
current version stops after first success

* tree optimization bug fix

---

.github/workflows/rust.yml
croaring/benches/benches.rs
croaring/src/bitmap/imp.rs
croaring/src/bitmap/iter.rs
croaring/src/bitmap/mod.rs
croaring/src/bitmap/ops.rs
croaring/src/treemap/imp.rs
croaring/src/treemap/iter.rs
croaring/src/treemap/mod.rs
croaring/src/treemap/serialization.rs
croaring/tests/lib.rs

Fix clippy and formatting (`fmt`) warnings.

Fix clippy and formatting

---

croaring/Cargo.toml
croaring/benches/benches.rs
croaring/benches/performance_comparison.rs

Allow running benchmarks on stable, and with more rigor

Convert benchmarks to criterion

---

croaring/src/bitmap/imp.rs
croaring/src/treemap/imp.rs

doc: correct return docs for run_optimize function

---

Cargo.lock
croaring/CHANGELOG.md
croaring/Cargo.toml
croaring/src/lib.rs

doc_auto_cfg has been merged into doc_cfg in https://github.com/rust-lang/rust/pull/138907

Fix docs rs
